spring.application.name=sharepoint
server.port=${APP_PORT:8080}
# Exception Handling
spring.web.resources.add-mappings=false
spring.mvc.throw-exception-if-no-handler-found=true
server.error.whitelabel.enabled=false
# SpringDoc / Swagger
security.jwt.cookie.secure=${JWT_COOKIE_SECURE:false}
springdoc.show-hateoas-endpoints=false
# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{requestId}] [%X{userEmail}] [%X{clientIp}] --- [%t] %-40.40logger{39} : %m%n